AllCops:
  TargetRubyVersion: 3.0
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 10
Style/Documentation:
  Enabled: false
Metrics/ClassLength:
  Max: 1000
Metrics/BlockLength:
  Max: 50
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity: 
  Max: 15